openapi: 3.1.0
info:
  title: Core platform - Accounting
  version: 1.0.0
  description: API used to manage the accounting context.
  contact:
    name: API Support
    url: https://developers.pismo.io/support/
  license:
    name: Copyright Pismo
servers:
  - url: https://sandbox.pismolabs.io/accounting
    description: Sandbox API server for testing
components:
  schemas:
    AccountingScriptV2:
      type: object
      properties:
        id:
          type: integer
          format: int64
        program_id:
          type: integer
          format: int64
        event_type_id:
          type: integer
          format: int64
        entry_type_id:
          type: integer
          format: int64
        debit_accounting:
          $ref: '#/components/schemas/AccountingAccountAccountSctiptPost'
        credit_accounting:
          $ref: '#/components/schemas/AccountingAccountAccountSctiptPost'
        cost_center:
          $ref: '#/components/schemas/CostCenterAccountingScriptPost'
        processing_code:
          type: string
        expression:
          type: string
          description: >
            Expression to calculate the value of the accounting entry. 

            It can be a simple mathematical expression or a more complex one
            using functions.
        fee_information:
          type: object
          description: |
            Information about the fee applied to the accounting entry.
            It can include details such as fee type, amount, and currency.
        parameters:
          $ref: '#/components/schemas/AccountingScriptParameters'
        cash_in_bucket:
          $ref: '#/components/schemas/AccountingScriptBucket'
        cash_out_bucket:
          $ref: '#/components/schemas/AccountingScriptBucket'
        is_database_stage:
          type: string
          description: >
            Indicates if the accounting script is for a database stage.

            If yes, the script is used for testing purposes and does not affect
            production data.
          default: 'no'
          example: 'yes'
        min_days_due:
          type: integer
          format: int64
          description: Minimum number of days for the due date.
          example: 30
        max_days_due:
          type: integer
          format: int64
          description: Maximum number of days for the due date.
          example: 90
        history:
          $ref: '#/components/schemas/History'
    AccountingScriptPostV2:
      type: object
      required:
        - program_id
        - event_type_id
        - entry_type_id
        - debit_accounting
        - credit_accounting
        - cost_center
        - parameters
      properties:
        program_id:
          type: integer
          format: int64
        event_type_id:
          type: integer
          format: int64
        entry_type_id:
          type: integer
          format: int64
        debit_accounting:
          $ref: '#/components/schemas/AccountingAccountAccountSctiptPost'
        credit_accounting:
          $ref: '#/components/schemas/AccountingAccountAccountSctiptPost'
        cost_center:
          $ref: '#/components/schemas/CostCenterAccountingScriptPost'
        processing_code:
          type: string
        expression:
          type: string
          description: >
            Expression to calculate the value of the accounting entry. 

            It can be a simple mathematical expression or a more complex one
            using functions.
        fee_information:
          type: object
          description: |
            Information about the fee applied to the accounting entry.
            It can include details such as fee type, amount, and currency.
        parameters:
          $ref: '#/components/schemas/AccountingScriptParameters'
        cash_in_bucket:
          $ref: '#/components/schemas/AccountingScriptBucket'
        cash_out_bucket:
          $ref: '#/components/schemas/AccountingScriptBucket'
        is_database_stage:
          type: string
          description: >
            Indicates if the accounting script is for a database stage.

            If yes, the script is used for testing purposes and does not affect
            production data.
          default: 'no'
          example: 'yes'
        min_days_due:
          type: integer
          format: int64
          description: Minimum number of days for the due date.
          example: 30
        max_days_due:
          type: integer
          format: int64
          description: Maximum number of days for the due date.
          example: 90
        reason:
          $ref: '#/components/schemas/HistoryReason'
        responsible:
          $ref: '#/components/schemas/HistoryResponsible'
    EventType:
      required:
        - id
        - description
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Event type ID
        description:
          type: string
          maximum: 100
          description: Event type description
      example:
        id: 101
        description: CREDIT
    EntryType:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/EntryTypeID'
        description:
          $ref: '#/components/schemas/EntryTypeDescription'
        type:
          $ref: '#/components/schemas/EntryTypeType'
        org_id:
          $ref: '#/components/schemas/OrgID'
        history:
          $ref: '#/components/schemas/History'
    EntryTypeDelete:
      required:
        - reason
      type: object
      properties:
        reason:
          $ref: '#/components/schemas/HistoryReason'
        responsible:
          $ref: '#/components/schemas/HistoryResponsible'
      example:
        reason: Deleting accounting entry type configuration.
        responsible: John Doe
    EntryTypeGetById:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/EntryTypeID'
        description:
          $ref: '#/components/schemas/EntryTypeDescription'
        type:
          $ref: '#/components/schemas/EntryTypeType'
        reason:
          $ref: '#/components/schemas/HistoryReason'
        responsible:
          $ref: '#/components/schemas/HistoryResponsible'
        history:
          type: array
          items:
            $ref: '#/components/schemas/History'
    EntryTypePost:
      required:
        - id
        - description
        - type
        - reason
      type: object
      properties:
        id:
          $ref: '#/components/schemas/EntryTypeID'
        description:
          $ref: '#/components/schemas/EntryTypeDescription'
        type:
          $ref: '#/components/schemas/EntryTypeType'
        reason:
          $ref: '#/components/schemas/HistoryReason'
        responsible:
          $ref: '#/components/schemas/HistoryResponsible'
    EntryTypePatch:
      required:
        - reason
      type: object
      properties:
        description:
          $ref: '#/components/schemas/EntryTypeDescription'
        type:
          $ref: '#/components/schemas/EntryTypeType'
        reason:
          $ref: '#/components/schemas/HistoryReason'
        responsible:
          $ref: '#/components/schemas/HistoryResponsible'
      example:
        description: DEBIT
        type: CREATION
        reason: Updating accounting entry type configuration.
        responsible: John Doe
    EntryTypeID:
      type: integer
      format: int64
      description: Entry type ID
      example: 101
    EntryTypeDescription:
      type: string
      maximum: 250
      description: Entry type description.
      example: CREDIT
    EntryTypeType:
      type: string
      maximum: 100
      description: >
        Set the entry type:


        * `CREATION`: Default value for new entries. Also, this value is assumed
        when type is not provided.

        * `DUE_DATE`: Used only with a credit program to indicate a due date
        entry.
      enum:
        - DUE_DATE
        - CREATION
      example: DUE_DATE
    OrgID:
      type: string
      description: Organization ID
      example: TN-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
    History:
      type: object
      description: Historical information for auditing the entity.
      properties:
        org_id:
          $ref: '#/components/schemas/OrgID'
        action:
          type: string
          description: Action performed on the entity.
          example: Created
        reason:
          $ref: '#/components/schemas/HistoryReason'
        responsible:
          $ref: '#/components/schemas/HistoryResponsible'
        version:
          type: integer
          format: int64
          description: Entity version.
          example: 1
        jsonb:
          type: string
          description: JSON representation of the request body.
          example: >-
            {"id": 101, "description": "CREDIT", "type": "DUE_DATE", "reason":
            "Creation of a new entry type configuration.", "responsible": "John
            Doe", "created_at": "2021-10-10T10:10:00Z"}
        created_at:
          type: string
          format: date-time
          description: >-
            Date and time when the history was created (ISO 8601). Format:
            YYYY-MM-DDThh:mm:ssZ.
          example: '2021-10-10T10:10:00Z'
    HistoryReason:
      type: string
      maximum: 250
      description: Reason for the operation.
      example: Creation of a new entry type configuration.
    HistoryResponsible:
      type: string
      maximum: 100
      description: User name or ID of the person performing the operation.
      example: John Doe
    AccountingAccount:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Accounting account ID
        description:
          type: string
          description: Description of the accounting account
          maximum: 100
        account:
          type: string
          description: Accounting account number
          maximum: 50
        program_id:
          type: integer
          format: int64
          description: Program ID
        created_at:
          type: string
          format: date-time
          description: Date and time when the accounting account was created (ISO 8601).
        deactivated_at:
          type: string
          format: date-time
          description: >-
            Date and time when the accounting account was deactivated (ISO
            8601). Filled when the account is deactivated.
      example:
        id: 1
        description: SAMPLE ACCOUNT
        account: 123123132-x
        program_id: 12
        created_at: '2021-10-10T10:10:00.000Z'
    AccountingAccountPost:
      required:
        - description
        - account
        - program_id
      type: object
      properties:
        description:
          type: string
          description: Description that helps to identify the accounting account
          maximum: 100
        account:
          type: string
          description: Accounting account number
          maximum: 50
        program_id:
          type: integer
          format: int64
          description: Related program ID
      example:
        description: SAMPLE ACCOUNT
        account: 123123132-x
        program_id: 12
    AccountingAccountAccountSctiptPost:
      required:
        - description
        - account
      type: object
      properties:
        description:
          type: string
          description: Description that helps to identify the accounting account
          maximum: 100
        account:
          type: string
          description: Accounting account number
          maximum: 50
        cosif:
          type: string
          description: Accounting account number
          maximum: 50
      example:
        description: SAMPLE ACCOUNT
        account: 123123132-x
        cosif: '1234567'
    AccountingAccountPatch:
      required:
        - description
      type: object
      properties:
        description:
          type: string
          description: Description that helps to identify the accounting account
          maximum: 100
      example:
        description: SAMPLE ACCOUNT
    CostCenter:
      required:
        - debit_org
        - credit_org
        - debit_cost
        - credit_cost
      type: object
      properties:
        debit_org:
          type: string
          maximum: 50
          description: Number of your Org’s debit accounting account
        credit_org:
          type: string
          maximum: 50
          description: Number of your Org’s credit accounting account
        debit_cost:
          type: string
          maximum: 50
          description: Number of the cost center of the debit accounting account
        credit_cost:
          type: string
          maximum: 50
          description: Number of the cost center of the credit accounting account
        deactivated_at:
          type: string
          format: date-time
          description: >-
            Date and time when the cost center was deactivated (ISO 8601).
            Filled when the account is deactivated.
      example:
        debit_org: '999999'
        credit_org: '999999'
        debit_cost: '999999'
        credit_cost: '999999'
        deactivated_at: '2021-10-10T10:10:00.000Z'
    CostCenterAccountingScriptPost:
      required:
        - debit_org
        - credit_org
        - debit_cost
        - credit_cost
      type: object
      properties:
        debit_org:
          type: string
          maximum: 50
          description: Number of your Org’s debit accounting account
        credit_org:
          type: string
          maximum: 50
          description: Number of your Org’s credit accounting account
        debit_cost:
          type: string
          maximum: 50
          description: Number of the cost center of the debit accounting account
        credit_cost:
          type: string
          maximum: 50
          description: Number of the cost center of the credit accounting account
      example:
        debit_org: '999999'
        credit_org: '999999'
        debit_cost: '999999'
        credit_cost: '999999'
    AccountingScriptPost:
      required:
        - program_id
        - event_type_id
        - entry_type_id
        - debit_accounting_account_id
        - credit_accounting_account_id
        - cost_center
      type: object
      properties:
        program_id:
          type: integer
          format: int64
          description: Related program ID
        event_type_id:
          type: integer
          format: int64
          description: Related event type ID
        entry_type_id:
          type: integer
          format: int64
          description: Related entry type ID
        entry_name:
          type: string
          enum:
            - amount
            - interest
            - iof
            - amount-dueDate
            - amount-clearing
            - amount-contract
            - deactivated
            - amount-cancelment-anticipation
            - amount-dueDate-cancelment
            - daily-interest
          default: amount
          description: Base entry ID. If not provided, 'amount' will be assumed.
        debit_accounting_account_id:
          type: integer
          format: int64
          description: Accounting account identifier assigned as debit account.
        credit_accounting_account_id:
          type: integer
          format: int64
          description: Accounting account identifier assigned as credit account.
        cost_center:
          $ref: '#/components/schemas/CostCenter'
        processing_code:
          type: string
          maximum: 6
          description: >-
            When the script is based on a processing code, this field is
            **REQUIRED**.
    AccountingScriptPatch:
      type: object
      properties:
        debit_account_number:
          type: string
          description: Debit account accounting number
        credit_account_number:
          type: string
          description: Credit account accounting number
        debit_cost:
          type: string
          description: Debit cost center
        credit_cost:
          type: string
          description: Credit cost center
    BatchAccountingScriptPatch:
      type: object
      properties:
        operations:
          type: array
          items:
            properties:
              accounting_script_id:
                type: integer
                format: int64
                description: Accounting script id
              set:
                $ref: '#/components/schemas/AccountingScriptPatch'
    AccountingScriptPatchResponse:
      type: object
      additionalProperties:
        type: object
        properties:
          has_error:
            description: Indicates whether an error occurred during the update process.
            type: boolean
          error_message:
            description: Provides a detailed description of the error encountered, if any.
            type: string
          new_id:
            type: integer
            format: int64
            description: >-
              Unique identifier of the newly created accounting script. (The old
              one will be deactivated)
    AccountingScriptSinglePatchResponse:
      type: object
      properties:
        new_id:
          type: integer
          format: int64
          description: >-
            Unique identifier of the newly created accounting script. (The old
            one will be deactivated)
    AccountingScript:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Account script ID
        program_id:
          type: integer
          format: int64
          description: Related program ID
        event_type_id:
          type: integer
          format: int64
          description: Related event type ID
        entry_type_id:
          type: integer
          format: int64
          description: Related entry type ID
        entry_name:
          type: string
          description: Base entry ID
        debit_accounting:
          $ref: '#/components/schemas/AccountingAccount'
        credit_accounting:
          $ref: '#/components/schemas/AccountingAccount'
        cost_center:
          $ref: '#/components/schemas/CostCenter'
        processing_code:
          type: string
          description: >-
            When the script is based on a processing code, this field is
            **REQUIRED**.
    AccountingEntryPost:
      required:
        - event_date
        - program_id
        - entry_type_id
        - amount
      type: object
      properties:
        event_date:
          type: string
          format: date
          description: Event date
          example: '2021-06-26T00:00:00.000Z'
        transaction_id:
          type: integer
          format: int64
          description: Related transaction ID
        account_id:
          type: integer
          format: int64
          description: Related account ID, required if Transaction_ID is present.
        program_id:
          type: integer
          format: int64
          description: Related program ID
        debit_accounting_account:
          type: string
          description: Debit accounting account
        credit_accounting_account:
          type: string
          description: Credit accounting account
        entry_type_id:
          type: integer
          format: int64
          description: Entry type ID
        amount:
          type: number
          description: Accounting entry amount
        tracking_id:
          type: string
          description: Tracking ID, optional idempotence key
          maximum: 50
      example:
        entry_type_id: 2100
        tracking_id: c5f2f677-d9aa-4285-8a08-d297a72d8949
        debit_accounting_account: '0'
        credit_accounting_account: '0'
        event_date: '2021-02-01T00:00:00.000Z'
        amount: 10
        program_id: 12
        transaction_id: 12342
        account_id: 21
    Bucket:
      type: object
      properties:
        name:
          type: string
          description: Bucket name
          example: bacen_pre_2039
        account:
          type: integer
          format: int64
          description: Account ID
          example: 123456
        value:
          type: number
          description: Bucket value
          example: 100
        updated_at:
          type: string
          format: date
          description: Bucket last updated date
          example: '2021-06-26T00:00:00.000Z'
    AccountingScriptBucket:
      type: object
      properties:
        name:
          type: string
          description: Bucket name
          example: bacen_pre_2039
        account:
          type: integer
          format: int64
          description: Account ID
          example: 123456
    AccountingScriptBucketResponse:
      type: object
      properties:
        name:
          type: string
          description: Bucket name
          example: bacen_pre_2039
        account:
          type: integer
          format: int64
          description: Account ID
          example: 123456
        currency:
          type: string
          description: Bucket currency
          example: BRL
        value:
          type: number
          description: Bucket value
          example: 100
    Page:
      type: object
      properties:
        has_next:
          type: boolean
          description: Indicates if there are more items to be retrieved.
        items:
          type: array
          description: Items retrieved from a given request.
          items:
            type: object
    AccountingScriptParameters:
      required:
        - name
        - value
      type: object
      properties:
        name:
          type: string
          description: Parameter name [pismo:timing or bacem:classification]
          example: pismo:timing
        value:
          type: string
          description: value of the parameter [REGULAR,DUEDATE OR TRUE OR 3]
          example: REGULAR,DUEDATE
  parameters:
    pageSize:
      in: query
      name: pageSize
      description: Maximum number of accounting event types per page.
      schema:
        type: integer
    pageOffset:
      name: pageOffset
      in: query
      description: >-
        Number to offset page resuts. For example, value `2` returns the third
        page. Defaults to `0`, which returns the first page.
      schema:
        type: integer
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: >-
        Account access token. Tokens can expire quickly, which can result in an
        "Unauthorized" error.
      bearerFormat: JWT
security:
  - BearerAuth: []
tags:
  - name: Accounting event types
    description: Endpoints to manage accounting event types.
  - name: Accounting entry types
    description: Endpoints to manage accounting entry types.
  - name: Accounting accounts
    description: >-
      Endpoints to manage the accounting plan, which is a set of accounting
      accounts.
  - name: Accounting scripts
    description: Endpoints to manage accounting scripts.
  - name: Accounting entry
    description: Endpoints to manage accounting entries.
  - name: Buckets
    description: Endpoints to manage account buckets.
paths:
  /v1/event-types:
    get:
      operationId: SearchEvents
      summary: List accounting event types
      description: >
        List accounting event types for your organization.


        Refer to the [Search for accounting event
        types](doc:search-for-accounting-event-types) for more information.
      tags:
        - Accounting event types
      parameters:
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/pageOffset'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: '#/components/schemas/Page'
                  - properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/EventType'
        '400':
          description: Bad request
      deprecated: false
  /v1/event-types/{eventTypeId}:
    get:
      operationId: GetEventTypeById
      summary: Get accounting event type
      description: >
        Get a specific accounting event type by its ID.


        Refer to the [Search for accounting event
        types](doc:search-for-accounting-event-types) for more information.
      tags:
        - Accounting event types
      parameters:
        - in: path
          name: eventTypeId
          schema:
            type: integer
            format: int64
          required: true
          description: Event type ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventType'
        '404':
          description: Event type not found
      deprecated: false
  /v1/entry-types:
    get:
      operationId: SearchEntryTypes
      summary: List accounting entry types (outdated)
      description: >
        List accounting entry types from your organization.


        This endpoint is outdated and new endpoint is available: [List
        accounting entry types](ref:searchentrytypesv2).


        Refer to [Search for accounting entry
        types](doc:create-accounting-entries#search-for-accounting-entry-types)
        for more information.
      tags:
        - Accounting entry types
      parameters:
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/pageOffset'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: '#/components/schemas/Page'
                  - properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/EntryType'
        '400':
          description: Bad request
      deprecated: false
  /v1/entry-types/{entryTypeId}:
    get:
      operationId: GetEntryTypeById
      summary: Get accounting entry type (outdated)
      description: >
        Get a specific accounting entry type by its ID.


        This endpoint is outdated and new endpoint is available: [Get accounting
        entry type](ref:getentrytypebyidv2).


        Refer to [Search for accounting entry
        types](doc:create-accounting-entries#search-for-accounting-entry-types)
        for more information.
      tags:
        - Accounting entry types
      parameters:
        - in: path
          name: entryTypeId
          schema:
            type: integer
            format: int64
          required: true
          description: Entry type ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntryType'
        '404':
          description: Entry type not found
      deprecated: false
  /v2/entry-types:
    post:
      operationId: CreateEntryTypeV2
      summary: Create accounting entry types
      description: Create accounting entry type for your organization.
      tags:
        - Accounting entry types
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntryTypePost'
      responses:
        '201':
          description: Ok
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/EntryType'
        '400':
          description: Bad request when a provided parameter is invalid
        '409':
          description: Bad request (conflict) when ID already exists
        '500':
          description: Internal server error
    get:
      operationId: SearchEntryTypesV2
      summary: List accounting entry types
      description: >-
        List accounting entry types with their latest history from your
        organization.
      tags:
        - Accounting entry types
      parameters:
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/pageOffset'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: '#/components/schemas/Page'
                  - properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/EntryType'
        '400':
          description: Bad request when a provided parameter is invalid
        '404':
          description: Entry type not found
        '500':
          description: Internal server error
      deprecated: false
  /v2/entry-types/{entryTypeId}:
    get:
      operationId: GetEntryTypeByIdV2
      summary: Get accounting entry type
      description: >-
        Get a specific accounting entry type by its ID with its historic
        information.
      tags:
        - Accounting entry types
      parameters:
        - in: path
          name: entryTypeId
          schema:
            type: integer
            format: int64
          required: true
          description: Numeric entry type ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntryTypeGetById'
        '400':
          description: Bad request when a provided parameter is invalid
        '404':
          description: Entry type not found
        '500':
          description: Internal server error
      deprecated: false
    patch:
      operationId: UpdateEntryTypeV2
      summary: Update accounting entry type
      description: Update a specific accounting entry type by its ID.
      tags:
        - Accounting entry types
      parameters:
        - in: path
          name: entryTypeId
          schema:
            type: integer
            format: int64
          required: true
          description: Numeric entry type ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntryTypePatch'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/EntryType'
        '400':
          description: Bad request when a provided parameter is invalid
        '404':
          description: Entry type not found
        '500':
          description: Internal server error
    delete:
      operationId: DeleteEntryTypeV2
      summary: Delete accounting entry type
      description: Delete a specific accounting entry type by its ID.
      tags:
        - Accounting entry types
      parameters:
        - in: path
          name: entryTypeId
          schema:
            type: integer
            format: int64
          required: true
          description: Numeric entry type ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntryTypeDelete'
      responses:
        '200':
          description: OK
        '400':
          description: Bad request when a provided parameter is invalid
        '404':
          description: Entry type not found
        '500':
          description: Internal server error
      deprecated: false
  /v1/accounting-accounts:
    post:
      operationId: CreateAccountingAccount
      summary: Create accounting account
      description: >
        Create an accounting account.


        Refer to the [Create an accounting
        account](doc:create-an-accounting-account) guide for more information.
      tags:
        - Accounting accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountingAccountPost'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountingAccount'
        '400':
          description: Bad request when some provided parameter is invalid.
        '409':
          description: Accounting account already exists.
    get:
      operationId: SearchAccountingAccounts
      summary: List accounting accounts
      description: List accounting accounts for your organization.
      tags:
        - Accounting accounts
      parameters:
        - in: query
          name: account
          description: >-
            Account ID filter to list all accounting accounts related to an
            account.
          schema:
            type: string
        - in: query
          name: programId
          description: >-
            Program ID filter to list all accounting accounts related to a
            program.
          schema:
            type: integer
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/pageOffset'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: '#/components/schemas/Page'
                  - properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/AccountingAccount'
        '400':
          description: Bad request
      deprecated: false
  /v1/accounting-accounts/{accountingAccountId}:
    get:
      operationId: GetAccountingAccountById
      summary: Get accounting account
      description: Get a specific accounting account by its ID.
      tags:
        - Accounting accounts
      parameters:
        - in: path
          name: accountingAccountId
          schema:
            type: integer
            format: int64
          required: true
          description: Accounting account ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountingAccount'
        '404':
          description: Accounting account not found.
      deprecated: false
    patch:
      operationId: UpdateAccountingAccount
      summary: Update accounting account
      description: Update description of an accounting account.
      tags:
        - Accounting accounts
      parameters:
        - in: path
          name: accountingAccountId
          schema:
            type: integer
            format: int64
          required: true
          description: Accounting account ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountingAccountPatch'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/AccountingAccount'
        '400':
          description: Bad request when a provided parameter is invalid.
        '404':
          description: Accounting account not found.
    delete:
      operationId: DeleteAccountingAccount
      summary: Delete accounting account
      description: Delete an accounting account.
      tags:
        - Accounting accounts
      parameters:
        - in: path
          name: accountingAccountId
          schema:
            type: integer
            format: int64
          required: true
          description: Accounting account ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                example:
                  id: 1
                  description: SAMPLE ACCOUNT
                  account: 123123132-x
                  program_id: 12
                  created_at: '2021-10-10T10:10:00.000Z'
                  deactivated_at: '2021-10-11T10:10:00.000Z'
        '404':
          description: Accounting account not found
        '409':
          description: >-
            Accounting account cannot be deleted, because it's being used by an
            active accounting script.
  /v1/accounting-scripts:
    post:
      operationId: CreateAccountingScript
      summary: Create accounting script
      description: >
        Create an accounting script. 


        Refer to the [Create an accounting
        script](doc:create-an-accounting-script) guide for more information.
      tags:
        - Accounting scripts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountingScriptPost'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountingScript'
        '400':
          description: Bad request when a provided parameter is invalid
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error description
                    example: Validation error, entry Type doesn't exists
        '409':
          description: Accounting script already exists
    get:
      operationId: SearchAccountingScript
      summary: List accounting scripts
      description: List existing accounting scripts for your organization.
      tags:
        - Accounting scripts
      parameters:
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/pageOffset'
        - in: query
          name: debitAccountingAccount
          description: List all accounting scripts related to a debit accounting account.
          schema:
            type: string
        - in: query
          name: creditAccountingAccount
          description: List all accounting scripts related to a credit accounting account.
          schema:
            type: string
        - in: query
          name: programId
          description: List all accounting scripts related to a program.
          schema:
            type: integer
            format: int64
        - in: query
          name: eventTypeId
          description: List all accounting scripts related to an event type.
          schema:
            type: integer
            format: int64
        - in: query
          name: entryTypeId
          description: List all accounting scripts related to an entry type.
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: '#/components/schemas/Page'
                  - properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/AccountingScript'
        '400':
          description: Bad request
      deprecated: false
  /v1/accounting-scripts/batch:
    patch:
      operationId: BatchUpdateAccountingScript
      summary: Update accounting scripts
      description: |
        Update accounting scripts.
      tags:
        - Accounting scripts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchAccountingScriptPatch'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountingScriptPatchResponse'
              example:
                '393028':
                  has_error: false
                  new_id: 403948
        '400':
          description: Bad request - invalid parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountingScriptPatchResponse'
              example:
                '393028':
                  has_error: true
                  error_message: Debit account not found
  /v1/buckets:
    get:
      operationId: GetBucketsByAccount
      summary: Get account buckets
      description: >
        Get one or all buckets for a specific tenant. Buckets are accumulators
        that are related to an accounting script. Buckets can have their values
        changed with each related accounting entry.
      tags:
        - Buckets
      parameters:
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/pageOffset'
        - in: query
          name: accountId
          schema:
            type: integer
          description: Account ID
        - in: query
          name: name
          schema:
            type: string
          required: false
          description: Bucket name
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: '#/components/schemas/Page'
                  - properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/Bucket'
        '400':
          description: Bad request
  /v1/accounting-scripts/{accountingScriptId}:
    get:
      operationId: GetAccountingScriptById
      summary: Get accounting script
      description: Get a specific accounting script by its ID.
      tags:
        - Accounting scripts
      parameters:
        - in: path
          name: accountingScriptId
          schema:
            type: integer
            format: int64
          required: true
          description: Accounting script ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountingScript'
        '404':
          description: Accounting script not found
      deprecated: false
    patch:
      operationId: UpdateAccountingScript
      summary: Update accounting script
      description: |
        Update accounting script.
      tags:
        - Accounting scripts
      parameters:
        - in: path
          name: accountingScriptId
          schema:
            type: integer
            format: int64
          required: true
          description: Accounting script ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountingScriptPatch'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountingScriptSinglePatchResponse'
              example:
                new_id: 403948
        '400':
          description: Bad request - invalid parameter
          content:
            application/json:
              example:
                message: Debit account not found
    delete:
      operationId: DeactivateAccountingScript
      summary: Deactivate accounting script
      description: Deactivate an accounting script by its ID.
      tags:
        - Accounting scripts
      parameters:
        - in: path
          name: accountingScriptId
          schema:
            type: integer
            format: int64
          required: true
          description: Numeric ID of the accounting script.
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountingScript'
        '404':
          description: Accounting script not found
  /v1/accounting-entries:
    post:
      operationId: CreateAccountingEntry
      summary: Create accounting entry
      description: >
        Create an accounting entry. 


        This endpoint generates an [Accounting entry
        created](https://developers.pismo.io/events/docs/accounting-entry-creation-1)
        event.


        Refer to the [Create accounting entries](doc:create-accounting-entries)
        guide for more information.
      tags:
        - Accounting entry
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountingEntryPost'
      responses:
        '202':
          description: Request accepted but not processed yet.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountingEntryPost'
        '400':
          description: Bad request when a provided parameter is invalid.
        '409':
          description: Conflict when TrackingId already exists.
  /v2/accounting-scripts:
    get:
      tags:
        - Accounting scripts
      summary: List Accounting Scripts
      operationId: listAccountingScriptsV2
      description: |
        List accounting scripts.
      parameters:
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/pageOffset'
        - in: query
          name: debitAccountingAccount
          description: List all accounting scripts related to a debit accounting account.
          schema:
            type: string
        - in: query
          name: creditAccountingAccount
          description: List all accounting scripts related to a credit accounting account.
          schema:
            type: string
        - in: query
          name: programId
          description: List all accounting scripts related to a program.
          schema:
            type: integer
            format: int64
        - in: query
          name: eventTypeId
          description: List all accounting scripts related to an event type.
          schema:
            type: integer
            format: int64
        - in: query
          name: entryTypeId
          description: List all accounting scripts related to an entry type.
          schema:
            type: integer
            format: int64
        - in: query
          name: cashInBucketName
          description: List all accounting scripts related to an cashin bucket name.
          schema:
            type: integer
            format: int64
        - in: query
          name: cashOutBucketName
          description: List all accounting scripts related to an cashout bucket name.
          schema:
            type: integer
            format: int64
        - in: query
          name: isStage
          description: List all accounting scripts of production or stage.
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: '#/components/schemas/Page'
                  - properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/AccountingScriptV2'
        '400':
          description: Bad request
      deprecated: false
    post:
      operationId: CreateAccountingScriptV2
      summary: Create accounting script
      description: >
        Create an accounting script. 


        Refer to the [Create an accounting
        script](doc:create-an-accounting-script) guide for more information.
      tags:
        - Accounting scripts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountingScriptPostV2'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountingScriptV2'
        '400':
          description: Bad request
        '409':
          description: Conflict
      deprecated: false
  /v2/accounting-scripts/{accountingScriptId}:
    get:
      tags:
        - Accounting scripts
      summary: Get Accounting Script by ID
      operationId: getAccountingScriptByIdV2
      parameters:
        - in: path
          name: accountingScriptId
          schema:
            type: integer
            format: int64
          required: true
          description: Accounting script ID
      responses:
        '200':
          description: Accounting script found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountingScriptV2'
        '404':
          description: Not found
      deprecated: false
