openapi: 3.1.0
info:
  title: Seller management - Merchant advancements
  version: 1.0.0
  description: >
    The Merchant advancements API offers clients a range of functions for
    managing advancements operations.
  contact:
    name: API Support
    url: https://developers.pismo.io/support
  license:
    name: Copyright Pismo
servers:
  - url: https://sandbox.pismolabs.io/merchants
    description: Sandbox API server for testing
tags:
  - name: Merchant advancement
    description: Endpoints for merchant advancements
  - name: Merchant advancement transaction
    description: Endpoints for merchant advancement transactions
components:
  parameters:
    advancementIdPath:
      description: Advancement request ID
      in: path
      name: advancementId
      required: true
      example: 10000
      schema:
        type: integer
        format: uint64
        minimum: 1
        maximum: 18446744073709552000
    AuthorizationHeader:
      description: Authorization token
      in: header
      name: Authorization
      required: true
      example: <your_token>
      schema:
        type: string
        description: Authorization token
        example: <your_token>
    confirmAdvancementQuery:
      description: >-
        Flag that indicates whether this is an effective advancement or just a
        simulation. The default value is `false`.
      in: query
      name: confirmAdvancement
      example: false
      schema:
        type: boolean
        description: >-
          When set to `true`, it means you are sending an actual advancement
          request (confirmed advancement); otherwise, it is a simulated
          advancement. The default value is `false`.
        default: false
        example: false
    marketplaceIdPath:
      description: Marketplace ID
      in: path
      name: marketplaceId
      required: true
      example: 1
      schema:
        type: integer
        format: uint64
        description: Marketplace ID
        minimum: 1
        maximum: 18446744073709552000
    merchantIdPath:
      description: Merchant ID
      in: path
      name: merchantId
      required: true
      example: 20
      schema:
        type: integer
        format: uint64
        description: Merchant ID
        minimum: 1
        maximum: 18446744073709552000
    startPaymentDateQuery:
      description: Date from which to search for a transaction
      in: query
      name: startPaymentDate
      example: '2023-10-05T00:00:00.000Z'
      schema:
        type: string
        format: date
        description: >
          If not sent, the default value for the start date is the next day.<br>

          The date format used is
          [ISO8601](https://en.wikipedia.org/wiki/ISO_8601).

          minLength: 10

          maxLength: 10
    endPaymentDateQuery:
      description: End date for searching transactions
      in: query
      name: endPaymentDate
      example: '2023-10-31T00:00:00.000Z'
      schema:
        type: string
        format: date
        description: >
          If not sent, the default end date value is the start day plus seven
          days.<br>

          The date format used is
          [ISO8601](https://en.wikipedia.org/wiki/ISO_8601).

          minLength: 10

          maxLength: 10
  schemas:
    CurrencyCode:
      description: >
        Represents the currency with an ISO-4217 alphabetic or numeric (3
        characters) string. For example, you represent Brazilian real with
        either BRL or 986.

        If you don't provide this code, the system uses the currency from the
        merchant program.
      type: string
      example: '986'
    CurrencyCodeResponse:
      description: |
        ISO-4217 alphabetic (3 characters) currency code.
      type: string
      example: BRL
    DefaultErrorResponse:
      type: object
      properties:
        code:
          type: string
          description: Pismo internal error code
        message:
          type: string
          description: Error message
        details:
          type: object
          description: If necessary, this field shows which fields failed validation
          properties:
            payload:
              type: array
              description: Array of fields with error
              items:
                type: object
                properties:
                  field:
                    type: string
                    description: Name of field with error
                  message:
                    type: string
                    description: Error Message referring to the field
    MerchantTransactionsResponse:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
            properties:
              scheduled_payment_date:
                type: string
                format: date
                description: Scheduling date for the next payment
              gross_value:
                type: string
                description: Merchant consolidated gross amount
              discount:
                type: string
                description: Merchant consolidated discount amount
              net_value:
                type: string
                description: Merchant consolidated net value
              details:
                type: array
                items:
                  type: object
                  properties:
                    merchant_id:
                      type: integer
                      description: ID of the merchant who owns the transaction
                    merchant_name:
                      type: string
                      description: Name of the merchant who owns the transaction
                    gross_value:
                      type: string
                      description: Total transaction gross amount
                    discount:
                      type: string
                      description: Total transaction discount amount
                    net_value:
                      type: string
                      description: Total transaction net amount
                    tax:
                      type: object
                      description: Taxes charged to the merchant
                      properties:
                        advancement_fee:
                          type: string
                          description: Fixed fee to be applied to the advancement request
                        discount_rate:
                          type: string
                          description: >-
                            Discount rate used to calculate the discount over
                            merchant advancements
                        maximum_advancement_percentage:
                          type: string
                          description: >-
                            Maximum allowable percentage of the net amount for
                            the advancement
        totals:
          type: object
          properties:
            gross_value:
              type: string
              description: Total consolidated gross amount
            discount:
              type: string
              description: Total consolidated discount amount
            net_value:
              type: string
              description: Total consolidated net value
    MerchantsAdvancementsRequest:
      type: object
      required:
        - begin_date
        - request_date
        - amount
        - real_time_settlement
      properties:
        begin_date:
          type: string
          format: date
          description: >-
            Used for searching merchant advancement requests. This is the start
            date of your search range.
          minLength: 10
          maxLength: 10
        request_date:
          type: string
          format: date
          description: Date for payment of the advancement
          minLength: 10
          maxLength: 10
        amount:
          type: number
          format: float
          description: Net amount to be paid in advance
          minimum: 1
          maximum: 4294967295
        currency_code:
          $ref: '#/components/schemas/CurrencyCode'
        real_time_settlement:
          type: boolean
          description: >-
            If `true`, the transaction is settled real-time; that is, at the
            exact moment. Default is `false`
          default: false
        end_date:
          type: string
          format: date
          description: >-
            Used for searching merchant advancement requests. This is the end
            date of your search range
          minLength: 10
          maxLength: 10
        campaign_advancement_fee:
          type: number
          format: float
          description: >-
            Campaign advancement fee to be applied to the current advancement
            request. It replaces the advancement fee set for the merchant in the
            request
          minimum: 1
          maximum: 4294967295
        campaign_discount_rate:
          type: number
          format: float
          description: >-
            Campaign discount rate to be applied to all merchants in the current
            advancement request
          minimum: 1
          maximum: 4294967295
        merchants:
          type: array
          items:
            type: object
            properties:
              merchant_id:
                type: integer
                format: uint64
                description: >-
                  Merchant ID of the advancement request. Must be the current
                  merchant or a branch of the current merchant
                minimum: 1
                maximum: 18446744073709552000
              campaign_discount_rate:
                type: number
                format: float
                description: Rate to be applied to a single merchant
                minimum: 1
                maximum: 4294967295
    TransactionsAdvancementsRequest:
      type: object
      required:
        - request_date
        - real_time_settlement
        - merchant_transaction_ids
      properties:
        request_date:
          type: string
          format: date
          description: Advancement payment date
          minLength: 10
          maxLength: 10
        real_time_settlement:
          type: boolean
          description: >-
            If `true`, the transaction is settled in realtime; that is, at the
            exact moment. The default is `false`.
          default: false
        merchant_transaction_ids:
          description: List of Merchant Transaction IDs
          type: array
          items:
            type: integer
            description: The transaction ID for merchant advancement
        campaign_advancement_fee:
          type: number
          format: float
          description: >-
            Campaign advancement fee applied to the current advancement request.
            It replaces the advancement fee set for the merchant in the request.
          minimum: 0
          maximum: 999999.99
        campaign_discount_rate:
          type: number
          format: float
          description: >-
            Campaign discount rate applied to all merchants in the current
            advancement request.
          minimum: 0
          maximum: 1
        merchants:
          type: array
          items:
            type: object
            properties:
              merchant_id:
                type: integer
                format: uint64
                description: >-
                  Merchant ID of the advancement request. Must be the current
                  merchant or a branch of the current merchant.
                minimum: 1
                maximum: 18446744073709552000
              campaign_discount_rate:
                type: number
                format: float
                description: Rate applied to a single merchant.
                minimum: 0
                maximum: 1
              merchant_transaction_ids:
                type: array
                description: List of Merchant Transaction IDs
                items:
                  type: integer
                  description: The transaction ID for merchant advancement
    MerchantsAdvancementsResponse:
      type: object
      properties:
        simulation_id:
          type: string
          description: >-
            A unique UUID generated for the simulated advancement. This field is
            only returned if it is a simulation
        advancement_request_id:
          type: integer
          description: >-
            This field is returned only if it's an actual advancement request
            (`EFFECTIVE`)
        type:
          type: string
          description: Operation type, returns either `SIMULATION` or `EFFECTIVE`
        currency_code:
          $ref: '#/components/schemas/CurrencyCodeResponse'
        begin_date:
          type: string
          format: date
          description: >-
            Used for searching merchant transactions. This is the start date of
            your search range
        end_date:
          type: string
          format: date
          description: >-
            Used for searching merchant transactions. This is the end date of
            your search range
        request_date:
          type: string
          format: date
          description: Advancement request date
    TransactionsAdvancementsResponse:
      type: object
      properties:
        simulation_id:
          type: string
          description: >-
            ID generated for the simulated advancement. This field is only
            returned if it is a simulation.
        advancement_request_id:
          type: integer
          description: >-
            This field is returned only if it's an actual advancement request
            (`EFFECTIVE`)
        type:
          type: string
          description: Operation type, returns either `SIMULATION` or `EFFECTIVE`
        request_date:
          type: string
          format: date
          description: Advancement request date
        currency_code:
          $ref: '#/components/schemas/CurrencyCodeResponse'
    AdvancementDataResponse:
      type: object
      properties:
        begin_date:
          type: string
          format: date
          description: Start date used to search merchant transactions
        end_date:
          type: string
          format: date
          description: End date used to search merchant transactions
        request_date:
          type: string
          format: date
          description: Advancement request date
        advanced_gross_amount:
          type: string
          description: >-
            Gross amount of the merchant advancement, including all applicable
            rates
        advanced_net_amount:
          type: string
          description: Advancement net amount
        advanced_discount_amount:
          type: string
          description: Total amount of advancement discount
        advancement_fee:
          type: string
          description: >-
            Fixed advancement rate, this field is omitted when you provide a
            value for `campaign_advancement_fee` in the request
        campaign_advancement_fee:
          type: string
          description: >-
            Fixed rate for requesting an advancement, this field is omitted when
            the it is not provided in the request
        interest_method:
          type: string
          enum:
            - SIMPLE
            - COMPOUND
            - SIMPLIFIED
          description: Type of interest. For example, compound or simple
        status:
          type: string
          enum:
            - PENDING
            - PROCESSED
            - ERROR
          description: Advancement status
        error_message:
          type: string
          description: >-
            Error message. It's omitted if the status is either `PROCESSED` or
            `PENDING`
        details:
          type: array
          description: >-
            Details are not sent when the request is either not processed or
            returns an error
          items:
            type: object
            properties:
              merchant_id:
                type: integer
                description: Merchant ID used in the advancement request
              merchant_name:
                type: string
                description: Merchant name
              advanced_gross_amount:
                type: string
                description: Total amount of advancement
              advanced_net_amount:
                type: string
                description: Net amount of advancement
              advanced_discount_amount:
                type: string
                description: Total discount amount
              discount_rate:
                type: string
                description: >-
                  Merchant discount rate, this field is omitted if the discount
                  rate is a campaign rate
              campaign_discount_rate:
                type: string
                description: >-
                  Campaign discount rate, this is omitted when the discount rate
                  is for the merchant
              maximum_advancement_percentage:
                type: string
                description: >-
                  Maximum allowable percentage of the net amount for the
                  advancement
              transaction_ids:
                type: array
                description: >-
                  Transaction ID used by the merchant who makes the advancement
                  request. This ID is generated by Pismo
                items:
                  type: integer
                  description: Transaction ID
  examples:
    DefaultErrorResponse:
      summary: Default Error Response
      value:
        code: EPT0303
        message: Failed during validation of request payload
        details:
          payload:
            - field: MerchantID
              message: Is not valid
            - field: MarketplaceID
              message: Is not valid
    MerchantTransactionsResponseSuccess:
      summary: Registration Response Success Example
      value:
        items:
          - scheduled_payment_date: '2023-10-29'
            gross_value: '250'
            discount: '8.25'
            net_value: '241.75'
            details:
              - merchant_id: 40305
                merchant_name: Merchant Name
                gross_value: '250'
                discount: '8.25'
                net_value: '241.75'
                tax:
                  advancement_fee: '0'
                  discount_rate: '0.05'
                  maximum_advancement_percentage: '1'
        totals:
          gross_value: '650'
          discount: '8.25'
          net_value: '641.75'
    MerchantsAdvancementsRequest:
      summary: Registration Response Success Example
      value:
        begin_date: '2023-08-01'
        end_date: '2023-08-31'
        request_date: '2023-08-10'
        amount: 100
        currency_code: BRL
        real_time_settlement: false
        campaign_advancement_fee: 5
        campaign_discount_rate: 1.024
        merchants:
          - merchant_id: 2
            campaign_discount_rate: 5
    TransactionsAdvancementsRequest:
      summary: Registration Response Success Example
      value:
        request_date: '2025-03-10'
        merchant_transaction_ids:
          - 111
          - 222
          - 333
        real_time_settlement: false
        campaign_advancement_fee: 5
        campaign_discount_rate: 0.036
        merchants:
          - merchant_id: 2
            campaign_discount_rate: 0.03
            merchant_transaction_ids:
              - 444
              - 555
    MerchantsAdvancementsResponseSuccess:
      summary: Registration Response Success Example
      value:
        simulation_id: a882e95e-5138-4e85-a89c-26778f2e4b14
        advancement_request_id: 1
        type: SIMULATION
        currency_code: BRL
        begin_date: '2023-08-01'
        end_date: '2023-08-31'
        request_date: '2023-08-10'
    TransactionsAdvancementsResponseSuccess:
      summary: Registration response succeeded
      value:
        simulation_id: a882e95e-5138-4e85-a89c-26778f2e4b14
        advancement_request_id: 1
        type: SIMULATION
        request_date: '2025-03-10'
        currency_code: BRL
    AdvancementDataResponseSuccess:
      summary: Registration Response Success Example
      value:
        begin_date: '2023-08-01'
        end_date: '2023-08-31'
        request_date: '2023-08-10'
        advanced_gross_amount: '355'
        advanced_net_amount: '300'
        advanced_discount_amount: '50'
        advancement_fee: '5'
        campaign_advancement_fee: '10'
        interest_method: SIMPLIFIED
        status: PROCESSED
        error_message: Creditor not found for merchant 2
        details:
          - merchant_id: 2
            merchant_name: Merchant Pismo 1
            advanced_gross_amount: '355'
            advanced_net_amount: '300'
            advanced_discount_amount: '50'
            discount_rate: '0.025'
            campaign_discount_rate: '0.025'
            maximum_advancement_percentage: '0.8'
            transaction_ids:
              - 12312323
              - 12312312312
paths:
  /v1/marketplaces/{marketplaceId}/merchants/{merchantId}/advancements:
    post:
      summary: Simulate merchant advancement
      operationId: merchants-advancements
      tags:
        - Merchant advancement
      description: >
        Create or simulate a merchant advancement request.  To trigger a
        simulated advancement request, you must include
        `confirmAdvancement=false` in the query. If you specify `true`, the
        advancement request becomes an actual request, not a simulation.<br>


        The endpoint enables a merchant to simulate an advancement scenario in
        order to validate whether or not there is enough balance in the account,
        as well as how much tax is anticipated. Since a simulated advancement is
        not a real advancement, it is not processed.


        A merchant advancement is sometimes called a prepayment of receivables.
        You arrange to have a financial institution make regular deposits into
        your account equal to what you expect to receive in the future from
        credit card sales in installments or post-dated

        checks and bills. The financial institution deducts its fee before it
        puts the money in your account. You pay back each deposit when you
        receive

        payment from your customers. This is a way of covering business expenses
        in the short term. It's a cheaper alternative to a loan.<br>


        <b>Note</b>:

        - If the merchant is the head merchant (also called a centralizer), the
        advanced amount is given to the head merchant instead of individual
        branch merchants, this is designed for better manageability.

        - If the commercial establishment is not registered as a headquarter or
        a branch in the current marketplace, the advancement is for a single
        commercial establishment.

        - The merchant must have sufficient balance in the account for the
        specified date range of the advancement.


        This endpoint generates a [Merchant advancement request
        created](https://developers.pismo.io/events/docs/merchants-advancement-request-1)
        event.
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
        - $ref: '#/components/parameters/marketplaceIdPath'
        - $ref: '#/components/parameters/merchantIdPath'
        - $ref: '#/components/parameters/confirmAdvancementQuery'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MerchantsAdvancementsRequest'
            examples:
              merchant-advancements-request:
                $ref: '#/components/examples/MerchantsAdvancementsRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MerchantsAdvancementsResponse'
              examples:
                merchant-advancement-response-success:
                  $ref: '#/components/examples/MerchantsAdvancementsResponseSuccess'
        '400':
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponse'
              examples:
                merchant-transactions-response-success:
                  $ref: '#/components/examples/DefaultErrorResponse'
  /v1/marketplaces/{marketplaceId}/merchants/{merchantId}/advancements/transactions:
    post:
      summary: Simulate transaction advancement
      operationId: merchant-transaction-advancement
      tags:
        - Merchant advancement
      description: >
        Create or simulate a merchant advancement request for specified
        transactions. You can select which transaction you want to advance by
        specifying a merchant transaction ID. To trigger a simulated advancement
        request, you must include `confirmAdvancement=false` in the query
        string. If you specify `true`, the advancement request becomes an actual
        request, not a simulation.<br>


        When a merchant advancement transaction is created, the endpoint
        produces [Merchant transaction
        created](https://developers.pismo.io/events/docs/merchants-merchant-transaction-created-1)
        and

        [Merchant advancement transaction
        created](https://developers.pismo.io/events/docs/merchants-advancement-transaction-create-1)
        events.
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
        - $ref: '#/components/parameters/marketplaceIdPath'
        - $ref: '#/components/parameters/merchantIdPath'
        - $ref: '#/components/parameters/confirmAdvancementQuery'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionsAdvancementsRequest'
            examples:
              transactions-advancements-request:
                $ref: '#/components/examples/TransactionsAdvancementsRequest'
      responses:
        '202':
          description: ACCEPTED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionsAdvancementsResponse'
              examples:
                transactions-advancement-response-success:
                  $ref: >-
                    #/components/examples/TransactionsAdvancementsResponseSuccess
        '400':
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponse'
              examples:
                transactions-advancement-response-success:
                  $ref: '#/components/examples/DefaultErrorResponse'
  /v1/marketplaces/{marketplaceId}/merchants/{merchantId}/advancements/{advancementId}:
    get:
      summary: Get advancement
      operationId: merchants-advancements-data
      tags:
        - Merchant advancement
      description: >
        Return information about an existing advancement. It returns fields such
        as dates, values, or status. If the advancement is only simulated but
        not yet in effect, the endpoint does not return any information.
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
        - $ref: '#/components/parameters/marketplaceIdPath'
        - $ref: '#/components/parameters/merchantIdPath'
        - $ref: '#/components/parameters/advancementIdPath'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdvancementDataResponse'
              examples:
                advancement-data-response-success:
                  $ref: '#/components/examples/AdvancementDataResponseSuccess'
        '400':
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponse'
              examples:
                merchant-transactions-response-success:
                  $ref: '#/components/examples/DefaultErrorResponse'
  /v1/marketplaces/{marketplaceId}/merchants/{merchantId}/transactions:
    get:
      summary: List transactions
      operationId: merchants-transactions
      tags:
        - Merchant advancement transaction
      description: >-
        Search for the balance of future schedules, consolidated by expected
        settlement date. In a head (centralizing) and branch (centralized)
        scenario, the transaction sum from all merchant branches is listed.
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
        - $ref: '#/components/parameters/marketplaceIdPath'
        - $ref: '#/components/parameters/merchantIdPath'
        - $ref: '#/components/parameters/startPaymentDateQuery'
        - $ref: '#/components/parameters/endPaymentDateQuery'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MerchantTransactionsResponse'
              examples:
                merchant-transactions-response-success:
                  $ref: '#/components/examples/MerchantTransactionsResponseSuccess'
        '400':
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponse'
              examples:
                merchant-transactions-response-success:
                  $ref: '#/components/examples/DefaultErrorResponse'
